on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

name: Build

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-pc-windows-gnu
      - run: ls ./target
      #- name: Archive
      #  uses: actions/upload-artifact@v3
      #  if: success()
      #  with:
      #    name: PowerNukkitX-Libs
      #    path: ./target/release
